<a href="https://colab.research.google.com/github/sowjanyasirigadde/TASK_AIML/blob/main/Presentation_Score_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
from google.colab import files
upload = files.upload()

Saving Presentation score_TASK.xlsx to Presentation score_TASK.xlsx

In [ ]:
df = pd.read_excel("Presentation score_TASK.xlsx")

# Check DataFrame
print(type(df))
print(df.head())
df.info()

<class 'pandas.core.frame.DataFrame'>
          UID       Participant Name Unnamed: 2  \
0         NaN                    NaN   Group No
1  T160600201        Gayathri Munasu          3
2  T160600202       Namratha Bajjuri          4
3  T160600203       Nikitha Sambangi        NaN
4  T160600204  Akhil Reddy Komireddy          3

                         Project Name Technical knowledge  Communication  \
0                                 NaN                  10           10.0
1  types of Data visuals,application                    6            6.0
2                Comparision of t-SNE                   6            6.0
3                                 NaN                 NaN            NaN
4                                 KNN                   6            7.0

   Attrire  Marks
0      5.0    NaN
1      3.0    NaN
2      4.0    NaN
3      NaN    NaN
4      3.0    NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UID                  71 non-null     object
 1   Participant Name     77 non-null     object
 2   Unnamed: 2           62 non-null     object
 3   Project Name         36 non-null     object
 4   Technical knowledge  61 non-null     object
 5   Communication        57 non-null     float64
 6   Attrire              55 non-null     float64
 7   Marks                0 non-null      float64
dtypes: float64(3), object(5)
memory usage: 5.4+ KB

### Data Cleaning and Preprocessing

In [ ]:
# Reload the data, assuming the first row (index 0) contains the correct headers
df = pd.read_excel('Presentation score_TASK.xlsx', header=0)

# The first data row (index 0 of the DataFrame) appears to be a summary/example row.
# We will drop this row to get to the actual participant data.
df = df.iloc[1:].copy()

# Rename the 'Unnamed: 2' column to 'Group No' and ensure other relevant columns are named correctly.
# Based on df.head() from initial load, the columns are already correct, but let's confirm explicit rename for robustness.
df.columns = ['UID', 'Participant Name', 'Group No', 'Project Name', 'Technical knowledge', 'Communication', 'Attire', 'Marks']

# Remove any extra spaces from column names that might have been introduced
df.columns = df.columns.str.strip()

# Display the cleaned DataFrame head and info
print('Cleaned DataFrame Head:')
display(df.head())
print('\nCleaned Column Information:')
df.info()

Cleaned DataFrame Head:

,UID,Participant Name,Group No,Project Name,Technical knowledge,Communication,Attire,Marks
1,T160600201,Gayathri Munasu,3,"types of Data visuals,application",6,6.0,3.0,NaN
2,T160600202,Namratha Bajjuri,4,Comparision of t-SNE,6,6.0,4.0,NaN
3,T160600203,Nikitha Sambangi,NaN,NaN,NaN,NaN,NaN,NaN
4,T160600204,Akhil Reddy Komireddy,3,KNN,6,7.0,3.0,NaN
5,T160600205,CHARAN KONDA,3,"Applications of SVM ,",6,7.0,3.0,NaN

Cleaned Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 1 to 84
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UID                  71 non-null     object
 1   Participant Name     77 non-null     object
 2   Group No             61 non-null     object
 3   Project Name         36 non-null     object
 4   Technical knowledge  60 non-null     object
 5   Communication        56 non-null     float64
 6   Attire               54 non-null     float64
 7   Marks                0 non-null      float64
dtypes: float64(3), object(5)
memory usage: 5.4+ KB

In [ ]:
# Convert 'Technical knowledge' to numeric, coercing errors to NaN
df['Technical knowledge'] = pd.to_numeric(df['Technical knowledge'], errors='coerce')

# Check for missing values before dropping
print('Missing Values Before Dropping:')
display(df.isnull().sum()[df.isnull().sum() > 0])

# Remove rows with any missing values from the relevant columns
initial_rows = df.shape[0]
df_cleaned = df.dropna(subset=['Technical knowledge', 'Communication', 'Attire']).copy()
rows_after_drop = df_cleaned.shape[0]

print(f"\nRemoved {initial_rows - rows_after_drop} rows with missing values in 'Technical knowledge', 'Communication', or 'Attire'.")
print(f"DataFrame shape after dropping NaNs: {df_cleaned.shape}")

# Display missing values after dropping
print('\nMissing Values After Dropping:')
display(df_cleaned.isnull().sum()[df_cleaned.isnull().sum() > 0])

Missing Values Before Dropping:

UID                    13
Participant Name        7
Group No               23
Project Name           48
Technical knowledge    28
Communication          28
Attire                 30
Marks                  84
dtype: int64

Removed 30 rows with missing values in 'Technical knowledge', 'Communication', or 'Attire'.
DataFrame shape after dropping NaNs: (54, 8)

Missing Values After Dropping:

Project Name    18
Marks           54
dtype: int64

### Create 'Total Marks' and Identify Top Students

In [ ]:
# Create 'Total Marks' column
df_cleaned['Total Marks'] = df_cleaned['Technical knowledge'] + df_cleaned['Communication'] + df_cleaned['Attire']

# 1. Top 5 students based on Total Marks
top_total_marks = df_cleaned.sort_values(by='Total Marks', ascending=False).head(5)
print('Top 5 students based on Total Marks:')
display(top_total_marks[['Participant Name', 'Total Marks']])

# 2. Top 5 students in Technical knowledge
top_technical = df_cleaned.sort_values(by='Technical knowledge', ascending=False).head(5)
print('\nTop 5 students in Technical knowledge:')
display(top_technical[['Participant Name', 'Technical knowledge']])

# 3. Top 5 students in Communication
top_communication = df_cleaned.sort_values(by='Communication', ascending=False).head(5)
print('\nTop 5 students in Communication:')
display(top_communication[['Participant Name', 'Communication']])

# 4. Top 5 students in Attire
top_attire = df_cleaned.sort_values(by='Attire', ascending=False).head(5)
print('\nTop 5 students in Attire:')
display(top_attire[['Participant Name', 'Attire']])

Top 5 students based on Total Marks:

                     Participant Name  Total Marks
7                    BOPPANI BHARGAVI         19.0
65                    Gajula Sathvika         19.0
23                    Kanigiri Devika         18.0
45  SRI SAI MADHURVIND MUDUTHANAPELLY         18.0
29               Mohammed Masoom Baba         18.0

Top 5 students in Technical knowledge:

                     Participant Name  Technical knowledge
7                    BOPPANI BHARGAVI                  8.0
45  SRI SAI MADHURVIND MUDUTHANAPELLY                  8.0
65                    Gajula Sathvika                  8.0
22                Madipadiga Kousheel                  7.0
19                  Rathakanti Rohith                  7.0

Top 5 students in Communication:

                Participant Name  Communication
5                   CHARAN KONDA            7.0
4          Akhil Reddy Komireddy            7.0
7               BOPPANI BHARGAVI            7.0
18  PEETHALA JYOTHI SWAROOP BABU            7.0
23               Kanigiri Devika            7.0

Top 5 students in Attire:

        Participant Name  Attire
36        Vaishnavi Erla     5.0
29  Mohammed Masoom Baba     5.0
6              Md Faisal     4.0
13    Akshitha Samudrala     4.0
2       Namratha Bajjuri     4.0

### Visualizations using Plotly

In [ ]:
# Plotly visualization for Top 5 students based on Total Marks (Horizontal Bar Chart)
fig = px.bar(top_total_marks.sort_values(by='Total Marks', ascending=True),
             x='Participant Name', y='Total Marks', orientation='v',
             title='Top 5 Students by Total Marks',
             labels={'Total Marks': 'Student', 'Total Marks': 'Score'},
             color='Total Marks', color_continuous_scale=px.colors.sequential.Viridis,
             text='Total Marks') # Display values on bars
fig.update_traces(textposition='outside')
fig.update_layout(xaxis_title='Student', yaxis_title='Score')
fig.show()

### Average Scores Visualization

In [ ]:
# Calculate the average for each relevant column
avg_technical = df_cleaned['Technical knowledge'].mean()
avg_communication = df_cleaned['Communication'].mean()
avg_attire = df_cleaned['Attire'].mean()

# Create a DataFrame for easy plotting
avg_scores_data = pd.DataFrame({
    'Category': ['Technical Knowledge', 'Communication', 'Attire'],
    'Average Score': [avg_technical, avg_communication, avg_attire]
})

# Plot the average scores using a pie chart
fig = px.pie(avg_scores_data, values='Average Score', names='Category',
             title='Average Scores Distribution for Technical Knowledge, Communication, and Attire',
             color='Category', color_discrete_sequence=px.colors.sequential.Viridis_r)

fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

Top 5 students in Technical knowledge

In [ ]:
# Plotly visualization for Top 5 students in Technical knowledge (Dot Plot/Scatter Plot)
fig = px.scatter(top_technical, x='Technical knowledge', y='Participant Name',
                 title='Top 5 Students by Technical Knowledge (Dot Plot)',
                 labels={'Participant Name': 'Student', 'Technical knowledge': 'Score'},
                 size='Technical knowledge', color='Technical knowledge',
                 color_continuous_scale=px.colors.sequential.Agsunset,
                 hover_name='Participant Name', text='Technical knowledge')
fig.update_traces(marker=dict(symbol='circle', size=15), textposition='middle right')
fig.update_layout(xaxis_title='Score', yaxis_title='Student',
                  xaxis_range=[min(top_technical['Technical knowledge']) - 1, max(top_technical['Technical knowledge']) + 1])
fig.show()

Top 5 students in Communication

In [ ]:
# Plotly visualization for Top 5 students in Communication (Pie Chart)
fig = px.pie(top_communication, values='Communication', names='Participant Name',
             title='Top 5 Students by Communication Score Distribution',
             color_discrete_sequence=px.colors.sequential.Inferno_r)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

Top 5 students in Attire

In [ ]:
fig = px.bar(top_attire.sort_values(by='Attire', ascending=True), # Sort for better visualization
             x='Attire', y='Participant Name', orientation='h',
             title='Top 5 Students by Attire (Horizontal Bar Chart)',
             labels={'Participant Name': 'Student', 'Attire': 'Score'},
             color='Attire', color_continuous_scale=px.colors.sequential.Plasma,
             text='Attire')
fig.update_traces(textposition='outside')
fig.update_layout(xaxis_title='Score', yaxis_title='Student')
fig.show()